### PR TITLE
Uploaded Feasibility Report v1.0

### PR DESCRIPTION
**Pull request by DaitTan**
Please suggest any changes and content for why we chose the idea.

### CODE REVIEW

**Comment by DaitTan** [comment]
#1

**Comment by akash1997** [comment]
fixes #1

**Comment by akash1997** [comment]
@mjvns @AnilSharma1997 @G-Megana @VikeshMeena Please review the document and submit your reviews soon.

**Comment by mjvns** [comment]
I think the front page of the document is completely fine..

**Comment by AnilSharma1997** [comment]
According to the point of view of our course, this document's front page is fine.

**Comment by AnilSharma1997** [comment]
Should we include the idea related to the busses's scheduling as we discussed?

**Comment by G-Megana** [comment]
It's "Megana Ganapathiraju"
Regarding the report, I have studied it and it's sufficient.

**Pull request merged**
